"""Shared format constants for SQLite database files."""

# === Database Header ===
HEADER_MAGIC = b"SQLite format 3\000"
HEADER_SIZE = 100

HEADER_OFFSET_MAGIC = 0
HEADER_OFFSET_PAGE_SIZE = 16
HEADER_OFFSET_WRITE_FORMAT = 18
HEADER_OFFSET_READ_FORMAT = 19
HEADER_OFFSET_RESERVED_SPACE = 20
HEADER_OFFSET_MAX_EMBEDDED = 21
HEADER_OFFSET_MIN_EMBEDDED = 22
HEADER_OFFSET_LEAF_PAYLOAD = 23
HEADER_OFFSET_FILE_CHANGE = 24
HEADER_OFFSET_DATABASE_SIZE = 28
HEADER_OFFSET_FREELIST_TRUNK = 32
HEADER_OFFSET_FREELIST_COUNT = 36
HEADER_OFFSET_SCHEMA_COOKIE = 40
HEADER_OFFSET_SCHEMA_FORMAT = 44
HEADER_OFFSET_DEFAULT_CACHE = 48
HEADER_OFFSET_LARGEST_ROOT = 52
HEADER_OFFSET_TEXT_ENCODING = 56
HEADER_OFFSET_USER_VERSION = 60
HEADER_OFFSET_INCREMENTAL_VACUUM = 64
HEADER_OFFSET_APPLICATION_ID = 68
HEADER_OFFSET_RESERVED = 72
HEADER_OFFSET_VERSION_VALID_FOR = 92
HEADER_OFFSET_SQLITE_VERSION = 96

# === Journal ===
JOURNAL_MAGIC = b"\xd9\xd5\x05\xf9\x20\xa1\x63\xd7"
JOURNAL_HEADER_SIZE = 28

# === Page Type Flags ===
PT_INTERIOR_INDEX = 0x02
PT_INTERIOR_TABLE = 0x05
PT_LEAF_INDEX = 0x0A
PT_LEAF_TABLE = 0x0D

# === Lock States ===
LOCK_NONE = 0
LOCK_SHARED = 1
LOCK_RESERVED = 2
LOCK_PENDING = 3
LOCK_EXCLUSIVE = 4

# === Text Encoding ===
ENCODING_UTF8 = 1
ENCODING_UTF16LE = 2
ENCODING_UTF16BE = 3

# === Defaults ===
DEFAULT_PAGE_SIZE = 4096
MIN_PAGE_SIZE = 512
MAX_PAGE_SIZE = 65536
MAX_EMBEDDED_PAYLOAD_FRACTION = 64
MIN_EMBEDDED_PAYLOAD_FRACTION = 32
LEAF_PAYLOAD_FRACTION = 32
MAX_COLUMNS = 2000
MAX_PAGE_COUNT = 1073741823
MAX_VARIABLE_NUMBER = 32766
MAX_TRIGGER_DEPTH = 1000
MAX_FUNCTION_ARG = 127

# === Serial Types ===
ST_NULL = 0
ST_INT8 = 1
ST_INT16 = 2
ST_INT24 = 3
ST_INT32 = 4
ST_INT48 = 5
ST_INT64 = 6
ST_FLOAT64 = 7
ST_ZERO = 8
ST_ONE = 9
ST_BLOB_BASE = 12
ST_TEXT_BASE = 13

# === Affinity ===
AFFINITY_INTEGER = 0
AFFINITY_REAL = 1
AFFINITY_NUMERIC = 2
AFFINITY_TEXT = 3
AFFINITY_BLOB = 4

# === Schema Table ===
SQLITE_SCHEMA_TABLE = "sqlite_schema"
SCHEMA_COL_TYPE = 0
SCHEMA_COL_NAME = 1
SCHEMA_COL_TBL_NAME = 2
SCHEMA_COL_ROOTPAGE = 3
SCHEMA_COL_SQL = 4
SCHEMA_NUM_COLUMNS = 5

# === Journal Mode ===
class JournalMode:
    DELETE = "DELETE"
    TRUNCATE = "TRUNCATE"
    PERSIST = "PERSIST"
    MEMORY = "MEMORY"
    OFF = "OFF"
    WAL = "WAL"

# === Open Flags ===
SQLITE_OPEN_READONLY = 0x01
SQLITE_OPEN_READWRITE = 0x02
SQLITE_OPEN_CREATE = 0x04

# === Sync Flags ===
SYNC_NORMAL = 0
SYNC_FULL = 1
SYNC_DATAONLY = 2
