from dataclasses import dataclass
from typing import Any


@dataclass
class Instruction:
    opcode: str
    P1: int = 0
    P2: int = 0
    P3: int = 0
    P4: Any = None
    P5: int = 0
    comment: str = ''


class Opcode:
    # Init / Halt
    Init = 'Init'
    Halt = 'Halt'

    # Cursor Operations
    OpenRead = 'OpenRead'
    OpenWrite = 'OpenWrite'
    OpenEphemeral = 'OpenEphemeral'
    OpenPseudo = 'OpenPseudo'
    OpenAutoindex = 'OpenAutoindex'
    OpenDup = 'OpenDup'
    Close = 'Close'
    Rewind = 'Rewind'
    Last = 'Last'
    Next = 'Next'
    Prev = 'Prev'
    SeekGT = 'SeekGT'
    SeekGE = 'SeekGE'
    SeekLT = 'SeekLT'
    SeekLE = 'SeekLE'
    SeekRowid = 'SeekRowid'
    IdxSeekGT = 'IdxSeekGT'
    IdxSeekGE = 'IdxSeekGE'
    IdxSeekLT = 'IdxSeekLT'
    IdxSeekLE = 'IdxSeekLE'
    NoConflictInsert = 'NoConflictInsert'
    IdxInsert = 'IdxInsert'
    IdxDelete = 'IdxDelete'
    IdxRowid = 'IdxRowid'
    Insert = 'Insert'
    Delete = 'Delete'
    NewRowid = 'NewRowid'
    Rowid = 'Rowid'
    RowData = 'RowData'
    Count = 'Count'
    Clear = 'Clear'

    # Record Operations
    MakeRecord = 'MakeRecord'
    Column = 'Column'
    Affinity = 'Affinity'
    TypeCheck = 'TypeCheck'
    Cast = 'Cast'

    # Comparison / Flow Control
    Eq = 'Eq'
    Ne = 'Ne'
    Lt = 'Lt'
    Le = 'Le'
    Gt = 'Gt'
    Ge = 'Ge'
    IsNull = 'IsNull'
    NotNull = 'NotNull'
    Compare = 'Compare'
    If = 'If'
    IfNot = 'IfNot'
    IfNotZero = 'IfNotZero'
    IfZero = 'IfZero'
    IfPos = 'IfPos'
    IfNeg = 'IfNeg'
    Once = 'Once'
    Goto = 'Goto'
    Gosub = 'Gosub'
    Return = 'Return'
    Yield = 'Yield'

    # Register Management
    Null = 'Null'
    Integer = 'Integer'
    Int64 = 'Int64'
    Real = 'Real'
    String = 'String'
    Blob = 'Blob'
    MemNull = 'MemNull'
    MemInt = 'MemInt'
    MemReal = 'MemReal'
    MemStr = 'MemStr'
    MemMove = 'MemMove'
    MemCopy = 'MemCopy'
    SCopy = 'SCopy'
    SoftNull = 'SoftNull'

    # Aggregation
    AggStep = 'AggStep'
    AggFinal = 'AggFinal'
    AggValue = 'AggValue'
    AggInvert = 'AggInvert'
    AggReset = 'AggReset'

    # Aggregation
    Aggregate = 'Aggregate'

    # Sorting
    SorterOpen = 'SorterOpen'
    SorterInsert = 'SorterInsert'
    SorterSort = 'SorterSort'
    SorterData = 'SorterData'
    SorterNext = 'SorterNext'
    SorterCompare = 'SorterCompare'

    # Transaction
    Transaction = 'Transaction'
    ReadCookie = 'ReadCookie'
    SetCookie = 'SetCookie'
    VerifyCookie = 'VerifyCookie'
    ParseSchema = 'ParseSchema'
    Savepoint = 'Savepoint'
    Release = 'Release'
    RollbackTo = 'RollbackTo'

    # I/O
    ResultRow = 'ResultRow'
    ResultColumn = 'ResultColumn'

    # DDL
    CreateTable = 'CreateTable'
    CreateIndex = 'CreateIndex'
    DropTable = 'DropTable'
    DropIndex = 'DropIndex'

    # Functions
    Function = 'Function'
    Function0 = 'Function0'
    AbsValue = 'AbsValue'
    Sin = 'Sin'
    Cos = 'Cos'
    Tan = 'Tan'
    Asin = 'Asin'
    Acos = 'Acos'
    Atan = 'Atan'
    Ceil = 'Ceil'
    Floor = 'Floor'
    Round = 'Round'
    Log = 'Log'
    Log10 = 'Log10'
    Sqrt = 'Sqrt'
    Exp = 'Exp'
    Pow = 'Pow'
    Pi = 'Pi'
    DateFunc = 'DateFunc'
    TimeFunc = 'TimeFunc'
    DateTimeFunc = 'DateTimeFunc'
    JulianDay = 'JulianDay'
    Strftime = 'Strftime'
    Like = 'Like'
    Glob = 'Glob'
    Regexp = 'Regexp'

    # Math
    Add = 'Add'
    Subtract = 'Subtract'
    Multiply = 'Multiply'
    Divide = 'Divide'
    Remainder = 'Remainder'
    Concat = 'Concat'
    BitAnd = 'BitAnd'
    BitOr = 'BitOr'
    ShiftLeft = 'ShiftLeft'
    ShiftRight = 'ShiftRight'

    # String
    Length = 'Length'
    Substr = 'Substr'
    Instr = 'Instr'
    ReplaceFunc = 'ReplaceFunc'
    Trim = 'Trim'
    LTrim = 'LTrim'
    RTrim = 'RTrim'
    Upper = 'Upper'
    Lower = 'Lower'
    Hex = 'Hex'
    Quote = 'Quote'
    Unicode = 'Unicode'
    Char = 'Char'

    # Numeric
    AbsValue = 'AbsValue'
    Round = 'Round'
    Ceil = 'Ceil'
    Floor = 'Floor'
    Trunc = 'Trunc'
    Coalesce = 'Coalesce'
    IfNull = 'IfNull'
    NullIf = 'NullIf'

    # Info
    Typeof = 'Typeof'
    LastInsertRowid = 'LastInsertRowid'
    Changes = 'Changes'

    # System
    SystemFunc = 'SystemFunc'
    PtTm = 'PtTm'

    # Cursor info
    PnNext = 'PnNext'
    ColumnCount = 'ColumnCount'
    Key = 'Key'
    NullRow = 'NullRow'
    SetMeta = 'SetMeta'

    # Integrity
    IntegrityCk = 'IntegrityCk'
    DecrJumpZero = 'DecrJumpZero'
    JumpZero = 'JumpZero'
    Move = 'Move'
    Copy = 'Copy'
    String8 = 'String8'
    ApplyAffinity = 'ApplyAffinity'
    MakeIdxRec = 'MakeIdxRec'
    Sort = 'Sort'
    SortNext = 'SortNext'
    Push = 'Push'
    Pop = 'Pop'
    Dup = 'Dup'
    Pull = 'Pull'
    Inj = 'Inj'
    ToText = 'ToText'
    ToBlob = 'ToBlob'
    ToNumeric = 'ToNumeric'
    ToInt = 'ToInt'
    ToReal = 'ToReal'
    Expire = 'Expire'
    Sequence = 'Sequence'
    Noop = 'Noop'
    Program = 'Program'
    Param = 'Param'
    FkCounter = 'FkCounter'
    FkIfZero = 'FkIfZero'
    FkCheck = 'FkCheck'
    BitNot = 'BitNot'
    MaxPgcnt = 'MaxPgcnt'
    InitCoroutine = 'InitCoroutine'
    EndCoroutine = 'EndCoroutine'
    Coroutine = 'Coroutine'
    RowSetAdd = 'RowSetAdd'
    RowSetRead = 'RowSetRead'
    RowSetTest = 'RowSetTest'
    SetSubtype = 'SetSubtype'
    Subtype = 'Subtype'
    SeekHit = 'SeekHit'
    SequenceTest = 'SequenceTest'
    BuiltinFunction = 'BuiltinFunction'
    ReadBtInfo = 'ReadBtInfo'
    WindowFunction = 'WindowFunction'
    WindowStep = 'WindowStep'
    WindowFinal = 'WindowFinal'
    Unpacked = 'Unpacked'
    Filter = 'Filter'
    SeekRowidEq = 'SeekRowidEq'
    BtreeInsert = 'BtreeInsert'
    BtreeDelete = 'BtreeDelete'
    BtreeCreateTable = 'BtreeCreateTable'
    BtreeCreateIndex = 'BtreeCreateIndex'
    BtreeDropTable = 'BtreeDropTable'
    BtreeDropIndex = 'BtreeDropIndex'
    BtreeClearTable = 'BtreeClearTable'
    RowCell = 'RowCell'
    DecodeRecord = 'DecodeRecord'
    RealToInt = 'RealToInt'
    IntToReal = 'IntToReal'
    StrLength = 'StrLength'
    StrSubstr = 'StrSubstr'
    StrReplace = 'StrReplace'
    StrTrim = 'StrTrim'
    StrUpper = 'StrUpper'
    StrLower = 'StrLower'
    StrInstr = 'StrInstr'
    StrHex = 'StrHex'
    StrQuote = 'StrQuote'
    StrUnicode = 'StrUnicode'
    StrChar = 'StrChar'
    StrLike = 'StrLike'
    StrGlob = 'StrGlob'
    StrRegexp = 'StrRegexp'
    FkUpdate = 'FkUpdate'
